// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 14.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Wilmar.Build.Core.Service.Default.ServiceTemplate
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Wilmar.Foundation;
    using Wilmar.Model.Core.Definitions;
    using Wilmar.Model.Core.Definitions.Entities;
    using Wilmar.Model.Core.Definitions.Entities.Members;
    using Wilmar.Model.Core.Definitions.Entities.Configure;
    using Wilmar.Compile.Core.Service.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class ControllerTemplate : ControllerTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.Text;
using System.Xml;
using System.Web.OData;
using System.Web.OData.Routing;
using System.Web.OData.Query;
using System.Web.Http;
using System.Net;
using System.Threading.Tasks;
using System.Data.Entity;
using Wilmar.");
            
            #line 25 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.Identity));
            
            #line default
            #line hidden
            this.Write(".Service.Models;\r\nusing Wilmar.Service.Common.ProjectBase;\r\nusing Wilmar.Service." +
                    "Common.ProjectBase.FilterExpression;\r\nusing Wilmar.Interface.Common;\r\n\r\nnamespac" +
                    "e Wilmar.");
            
            #line 30 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.Identity));
            
            #line default
            #line hidden
            this.Write(".Service.Controllers\r\n{\r\n\t");
            
            #line 32 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.GenerateCode()));
            
            #line default
            #line hidden
            this.Write("\r\n\tpublic class ");
            
            #line 33 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.ClassName));
            
            #line default
            #line hidden
            this.Write(" : EntitySetController<");
            
            #line 33 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.Entity.DataContext.ClassName));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 33 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.Entity.ClassName));
            
            #line default
            #line hidden
            this.Write("> \r\n\t{\r\n");
            
            #line 35 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
 foreach (var method in Data.Methods) {
    switch (method.MethodType) {
        case EControllerMethodType.GetQueryable:
            
            #line default
            #line hidden
            
            #line 38 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
 if(!Data.Entity.IsDimFast){ 
            
            #line default
            #line hidden
            this.Write("\t\tprivate void Get(ref IQueryable<");
            
            #line 39 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Documnet.Name));
            
            #line default
            #line hidden
            this.Write("> query)\r\n\t\t{\r\n\t\t\t");
            
            #line 41 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Configure.GetInterceptor==null?"": Configure.GetInterceptor));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t}\r\n");
            
            #line 43 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\r\n");
            
            #line 45 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
 if(Data.Entity.IsDimFast){ 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 46 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(WriteDimFastHelper()));
            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic IQueryable<");
            
            #line 47 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Documnet.Name));
            
            #line default
            #line hidden
            this.Write("DimProxy> Get(ODataQueryOptions<");
            
            #line 47 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Documnet.Name));
            
            #line default
            #line hidden
            this.Write("DimProxy> queryOptions)\r\n\t\t{\r\n\t\t\t");
            
            #line 49 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(WriteDimFastQuery()));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t}\r\n");
            
            #line 51 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 52 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.GenerateCode()));
            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic IQueryable<");
            
            #line 53 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Documnet.Name));
            
            #line default
            #line hidden
            this.Write("> Get()\r\n\t\t{\r\n\t\t\tvar _Query = this.Query;\r\n\t\t\tGet(ref _Query);\r\n");
            
            #line 57 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
 if (Configure.QueryFilter != null && Configure.QueryFilter.Filters.Count > 0) {
		WriteFilterCode(Configure.QueryFilter); 
	} 
            
            #line default
            #line hidden
            this.Write("\t\t\treturn _Query.AsNoTracking();\r\n\t\t}\r\n");
            
            #line 62 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 63 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            break;
        case EControllerMethodType.GetSingleResult:
            
            #line default
            #line hidden
            
            #line 65 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
 if(!Data.Entity.IsDimFast){ 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 66 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.GenerateCode()));
            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic SingleResult<");
            
            #line 67 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Documnet.Name));
            
            #line default
            #line hidden
            this.Write("> Get(");
            
            #line 67 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.EntityKeyParameter));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\tvar _Query = this.Query;\r\n\t\t\tGet(ref _Query);\r\n");
            
            #line 71 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
 if (Configure.QueryFilter != null && Configure.QueryFilter.Filters.Count > 0) {
		WriteFilterCode(Configure.QueryFilter); 
	} 
            
            #line default
            #line hidden
            this.Write("\t\t\treturn SingleResult.Create(_Query.Where(");
            
            #line 74 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.EntityLinqWhere));
            
            #line default
            #line hidden
            this.Write(").AsNoTracking());\r\n\t\t}\r\n");
            
            #line 76 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 77 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            break;
        case EControllerMethodType.GetNavigateQueryable:
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 80 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.GenerateCode()));
            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic IQueryable<");
            
            #line 81 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Navigation.ToEntity.ClassName));
            
            #line default
            #line hidden
            this.Write("> Get");
            
            #line 81 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Navigation.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 81 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.EntityKeyParameter));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t    return EntitySet.Where(");
            
            #line 83 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.EntityLinqWhere));
            
            #line default
            #line hidden
            this.Write(").SelectMany(m => m.");
            
            #line 83 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Navigation.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t}\r\n");
            
            #line 85 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            break;
        case EControllerMethodType.GetNavigateSingleResult:
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 88 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.GenerateCode()));
            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic SingleResult<");
            
            #line 89 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Navigation.ToEntity.ClassName));
            
            #line default
            #line hidden
            this.Write("> Get");
            
            #line 89 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Navigation.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 89 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.EntityKeyParameter));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t    return SingleResult.Create(EntitySet.Where(");
            
            #line 91 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.EntityLinqWhere));
            
            #line default
            #line hidden
            this.Write(").Select(m => m.");
            
            #line 91 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Navigation.Name));
            
            #line default
            #line hidden
            this.Write("));\r\n\t\t}\r\n");
            
            #line 93 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            break;
        case EControllerMethodType.Post:
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 96 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.GenerateCode()));
            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic async Task<IHttpActionResult> Post(");
            
            #line 97 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Documnet.Name));
            
            #line default
            #line hidden
            this.Write(" entity)\r\n\t\t{\r\n\t\t\treturn await PostEntity(entity);\r\n\t\t}\r\n");
            
            #line 101 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            break;
        case EControllerMethodType.Delete:
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 104 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.GenerateCode()));
            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic async Task<IHttpActionResult> Delete(");
            
            #line 105 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.EntityKeyParameter));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\treturn await DeleteEntity(");
            
            #line 107 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.EntityLinqWhere));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t}\r\n");
            
            #line 109 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            break;
        case EControllerMethodType.Put:
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 112 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.GenerateCode()));
            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic async Task<IHttpActionResult> Put(");
            
            #line 113 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.EntityKeyParameter));
            
            #line default
            #line hidden
            this.Write(", Delta<");
            
            #line 113 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Documnet.Name));
            
            #line default
            #line hidden
            this.Write("> patch)\r\n\t\t{\r\n\t\t\treturn  await PutEntity(");
            
            #line 115 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.EntityLinqWhere));
            
            #line default
            #line hidden
            this.Write(", patch);\r\n\t\t}\r\n");
            
            #line 117 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            break;
        case EControllerMethodType.Patch:
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 120 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.GenerateCode()));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t[AcceptVerbs(\"PATCH\", \"MERGE\")]\r\n\t\tpublic async Task<IHttpActionResult> Patch" +
                    "(");
            
            #line 122 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.EntityKeyParameter));
            
            #line default
            #line hidden
            this.Write(", Delta<");
            
            #line 122 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Documnet.Name));
            
            #line default
            #line hidden
            this.Write("> data)\r\n\t\t{\r\n\t\t\treturn await PatchEntity(");
            
            #line 124 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.EntityLinqWhere));
            
            #line default
            #line hidden
            this.Write(", data);\r\n\t\t}\r\n");
            
            #line 126 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            break;
        case EControllerMethodType.CreateRef:
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 129 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.GenerateCode()));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t[AcceptVerbs(\"POST\", \"PUT\")]\r\n\t\tpublic async Task<IHttpActionResult> CreateRe" +
                    "f(");
            
            #line 131 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.EntityKeyParameter));
            
            #line default
            #line hidden
            this.Write(", string navigationProperty, [FromBody] Uri link)\r\n\t\t{\r\n\t\t\tSystem.Diagnostics.Deb" +
                    "ug.WriteLine(\"----------");
            
            #line 133 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Documnet.Name));
            
            #line default
            #line hidden
            this.Write("__CreateRef\");\r\n\t\t\treturn await base.CreateRef(");
            
            #line 134 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.EntityLinqWhere));
            
            #line default
            #line hidden
            this.Write(", navigationProperty, link);\r\n\t\t}\r\n");
            
            #line 136 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            break;
        case EControllerMethodType.DeleteRef1:
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 139 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.GenerateCode()));
            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic async Task<IHttpActionResult> DeleteRef(");
            
            #line 140 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.EntityKeyParameter));
            
            #line default
            #line hidden
            this.Write(", string navigationProperty, [FromBody] Uri link)\r\n\t\t{\r\n\t\t\tSystem.Diagnostics.Deb" +
                    "ug.WriteLine(\"----------");
            
            #line 142 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Documnet.Name));
            
            #line default
            #line hidden
            this.Write("__DeleteRef\");\r\n\t\t\treturn await base.DeleteRef(");
            
            #line 143 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.EntityLinqWhere));
            
            #line default
            #line hidden
            this.Write(", navigationProperty);\r\n\t\t}\r\n");
            
            #line 145 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            break;
        case EControllerMethodType.DeleteRef2:
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 148 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.GenerateCode()));
            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic async Task<IHttpActionResult> DeleteRef(");
            
            #line 149 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.EntityKeyParameter));
            
            #line default
            #line hidden
            this.Write(", [FromODataUri] string relatedKey, string navigationProperty)\r\n\t\t{\r\n\t\t\tSystem.Di" +
                    "agnostics.Debug.WriteLine(\"----------");
            
            #line 151 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Documnet.Name));
            
            #line default
            #line hidden
            this.Write("__DeleteRef\");\r\n\t\t\treturn await base.DeleteRef(");
            
            #line 152 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.EntityLinqWhere));
            
            #line default
            #line hidden
            this.Write(", navigationProperty, relatedKey);\r\n\t\t}\r\n");
            
            #line 154 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            break;
        case EControllerMethodType.CustomAction: var action = method.Action; 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 157 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.GenerateCode()));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t[HttpPost]\r\n\t\tpublic async Task<IHttpActionResult> ");
            
            #line 159 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 159 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(!action.Source.IsCollectionInvoke ? ( Data.EntityKeyParameter + "," ) : ""));
            
            #line default
            #line hidden
            this.Write("ODataActionParameters __params)\r\n\t\t{\r\n");
            
            #line 161 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
		foreach (var para in action.Parameters) { 
            
            #line default
            #line hidden
            
            #line 162 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
			if(!para.Value.IsEntityType) { 
            
            #line default
            #line hidden
            this.Write("\t\t\tvar ");
            
            #line 163 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(para.Key));
            
            #line default
            #line hidden
            this.Write(" = (");
            
            #line 163 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(para.Value.TypeName));
            
            #line default
            #line hidden
            this.Write(")__params[\"");
            
            #line 163 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(para.Key));
            
            #line default
            #line hidden
            this.Write("\"];\r\n");
            
            #line 164 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
			} else if(para.Value.IsCollection) { 
            
            #line default
            #line hidden
            this.Write("\t\t\tvar ");
            
            #line 165 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(para.Key));
            
            #line default
            #line hidden
            this.Write(" = __params[\"");
            
            #line 165 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(para.Key));
            
            #line default
            #line hidden
            this.Write("\"] as System.Collections.Generic.IEnumerable<");
            
            #line 165 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(para.Value.TypeName));
            
            #line default
            #line hidden
            this.Write(">;\r\n");
            
            #line 166 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
			} else { 
            
            #line default
            #line hidden
            this.Write("\t\t\tvar ");
            
            #line 167 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(para.Key));
            
            #line default
            #line hidden
            this.Write(" = __params[\"");
            
            #line 167 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(para.Key));
            
            #line default
            #line hidden
            this.Write("\"] as ");
            
            #line 167 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(para.Value.TypeName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 168 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
			} 
            
            #line default
            #line hidden
            
            #line 169 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
		} 
            
            #line default
            #line hidden
            this.Write("\t\t\tSystem.Diagnostics.Debug.WriteLine(\"----------");
            
            #line 170 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Documnet.Name));
            
            #line default
            #line hidden
            this.Write("__");
            
            #line 170 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t");
            
            #line 171 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Source.Body ?? ""));
            
            #line default
            #line hidden
            this.Write("\t \r\n");
            
            #line 172 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
		if (action.ReturnType == null || string.IsNullOrEmpty(action.Source.Body)) { 
            
            #line default
            #line hidden
            this.Write("\t\t\treturn  StatusCode(HttpStatusCode.NoContent);\r\n");
            
            #line 174 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
		} 
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n");
            
            #line 176 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            break;
        case EControllerMethodType.OnCreateEntity:
            
            #line default
            #line hidden
            this.Write("\t\tprotected override void OnCreateEntity(");
            
            #line 178 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Documnet.Name));
            
            #line default
            #line hidden
            this.Write(" entity, EntityOperationArgs args) \r\n\t\t{ \r\n");
            
            #line 180 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
		foreach (var metdata in Data.InheritEntitys) {
			var entity = metdata.Definition; 
            
            #line default
            #line hidden
            
            #line 182 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
		foreach (var pro in entity.Members.OfType<PrimaryMember>().Where(a => a.GenerateMode == EPrimaryGenerateMode.Code)) { 
            
            #line default
            #line hidden
            this.Write("\t\t\tentity.");
            
            #line 183 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pro.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 183 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pro.CreateGenerate));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 184 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
		} 
            
            #line default
            #line hidden
            this.Write("     \r\n");
            
            #line 185 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
		foreach (var pro in entity.Members.OfType<ColumnMember>().Where(a => a.GenerateMode == EColumnGenerateMode.CodeCreate || a.GenerateMode == EColumnGenerateMode.CodeCreateUpdate)) { 
            
            #line default
            #line hidden
            this.Write("\t\t\tentity.");
            
            #line 186 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pro.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 186 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pro.CreateGenerate));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 187 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
		} 
            
            #line default
            #line hidden
            this.Write("  \r\n");
            
            #line 188 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
			var configure = entity.Controller;
			if (configure != null) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 190 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(configure.PostInterceptor ?? ""));
            
            #line default
            #line hidden
            this.Write("          \r\n");
            
            #line 191 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
			}
		} 
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n");
            
            #line 194 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            break;


        case EControllerMethodType.OnUpdateEntity:
            
            #line default
            #line hidden
            this.Write("\t\tprotected override void OnUpdateEntity(");
            
            #line 198 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Documnet.Name));
            
            #line default
            #line hidden
            this.Write(" entity, EntityOperationArgs args) \r\n\t\t{ \r\n");
            
            #line 200 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
		foreach (var metdata in Data.InheritEntitys) {
			var entity = metdata.Definition; 
            
            #line default
            #line hidden
            
            #line 202 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
		foreach (var pro in entity.Members.OfType<ColumnMember>().Where(a => a.GenerateMode == EColumnGenerateMode.CodeCreate)) { 
            
            #line default
            #line hidden
            this.Write("\t\t\tDataContext.Entry<");
            
            #line 203 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Documnet.Name));
            
            #line default
            #line hidden
            this.Write(">(entity).Property(\"");
            
            #line 203 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pro.Name));
            
            #line default
            #line hidden
            this.Write("\").IsModified = false;\r\n");
            
            #line 204 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
		} 
            
            #line default
            #line hidden
            
            #line 205 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
		foreach (var pro in entity.Members.OfType<ColumnMember>().Where(a => a.GenerateMode == EColumnGenerateMode.CodeUpdate || a.GenerateMode == EColumnGenerateMode.CodeCreateUpdate)) { 
            
            #line default
            #line hidden
            this.Write("\t\t\tentity.");
            
            #line 206 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pro.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 206 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pro.CreateGenerate));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 207 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
		} 
            
            #line default
            #line hidden
            
            #line 208 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
			var configure = entity.Controller;
			if (configure != null) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 210 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(configure.PutInterceptor ?? ""));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 211 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
			}
		} 
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n");
            
            #line 214 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            break;
        case EControllerMethodType.OnDeleteEntity:
            
            #line default
            #line hidden
            this.Write("\t\tprotected override void OnDeleteEntity(");
            
            #line 216 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Documnet.Name));
            
            #line default
            #line hidden
            this.Write(" entity, EntityOperationArgs args) \r\n\t\t{ \r\n");
            
            #line 218 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
		foreach (var metdata in Data.InheritEntitys) {
			var configure = metdata.Definition.Controller;
			if (configure != null) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 221 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(configure.DeleteInterceptor ?? ""));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 222 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
			}
		} 
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n");
            
            #line 225 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            break;
        case EControllerMethodType.CreateRefOverride:
            
            #line default
            #line hidden
            this.Write("\r\n\t\tprotected override bool CreateRef(");
            
            #line 228 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Documnet.Name));
            
            #line default
            #line hidden
            this.Write(" entity, string navigationProperty, Uri link)\r\n\t\t{\r\n\t\t\tobject target = null;\r\n\t\t " +
                    "   switch (navigationProperty)\r\n\t\t    {\r\n");
            
            #line 233 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
	foreach (var member in Data.Entity.NavigationPropertys.Values) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\tcase \"");
            
            #line 234 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write("\":\r\n\t\t\t\t\t\ttarget = GetLinkTarget<");
            
            #line 235 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ToEntity.ClassName));
            
            #line default
            #line hidden
            this.Write(">(link);\r\n");
            
            #line 236 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
		if (member.PropertyType.IsCollection) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\tentity.");
            
            #line 237 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write(".Add((");
            
            #line 237 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ToEntity.ClassName));
            
            #line default
            #line hidden
            this.Write(")target);\r\n");
            
            #line 238 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
		} else { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\tentity.");
            
            #line 239 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write(" = (");
            
            #line 239 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ToEntity.ClassName));
            
            #line default
            #line hidden
            this.Write(")target;\r\n");
            
            #line 240 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
		} 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\tbreak;\r\n");
            
            #line 242 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
	} 
            
            #line default
            #line hidden
            this.Write("\t\t\t\tdefault:\r\n\t\t\t\t\treturn base.CreateRef(entity, navigationProperty, link);\r\n    " +
                    "        }\r\n");
            
            #line 246 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
	if (Entity.Controller != null) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 247 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Controller.CreateRefInterceptor ?? ""));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 248 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
	} 
            
            #line default
            #line hidden
            this.Write("            return true;\r\n        }\r\n");
            
            #line 251 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            break;
        case EControllerMethodType.DeleteRefOverride:
            
            #line default
            #line hidden
            this.Write("\r\n\t\tprotected override bool DeleteRef(");
            
            #line 254 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Documnet.Name));
            
            #line default
            #line hidden
            this.Write(" entity, string navigationProperty, string[] relatedKeys)\r\n        {\r\n\t\t\tobject t" +
                    "arget = null;\r\n            switch (navigationProperty)\r\n            {\r\n");
            
            #line 259 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
	foreach (var member in Data.Entity.NavigationPropertys.Values) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\tcase \"");
            
            #line 260 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write("\":\r\n");
            
            #line 261 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
		if (member.PropertyType.IsCollection) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\ttarget = DataContext.");
            
            #line 262 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ToEntity.ClassName));
            
            #line default
            #line hidden
            this.Write("s.Find(");
            
            #line 262 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateNavigateFindParameter(member)));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\t\t\tentity.");
            
            #line 263 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write(".Remove((");
            
            #line 263 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ToEntity.ClassName));
            
            #line default
            #line hidden
            this.Write(")target);\r\n");
            
            #line 264 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
		} else { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\tDataContext.Entry(entity).Reference<");
            
            #line 265 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ToEntity.ClassName));
            
            #line default
            #line hidden
            this.Write(">(\"");
            
            #line 265 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write("\").Load();\r\n\t\t\t\t\tentity.");
            
            #line 266 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write(" = null;\r\n");
            
            #line 267 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
		} 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\tbreak;\r\n");
            
            #line 269 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
	} 
            
            #line default
            #line hidden
            this.Write("                default:\r\n                    return base.DeleteRef(entity, navig" +
                    "ationProperty, relatedKeys);\r\n            }\r\n");
            
            #line 273 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
	if (Entity.Controller != null) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 274 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Controller.DeleteRefInterceptor ?? ""));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 275 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
	} 
            
            #line default
            #line hidden
            this.Write("            return true;\r\n        }\r\n");
            
            #line 278 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            break;
    }
} 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 282 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
 if (Data.UpdateEntityCommonPropertyPerssions.Count > 0) { 
            
            #line default
            #line hidden
            this.Write(@"        protected override Dictionary<int, string> UpdateEntityCommonPropertyPermissions
        {
            get { return _UpdateEntityCommonPropertyPermissions; }
        }
        private static readonly Dictionary<int, string> _UpdateEntityCommonPropertyPermissions = new Dictionary<int, string>()
        {
");
            
            #line 289 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
		foreach (var item in Data.UpdateEntityCommonPropertyPerssions) {
            
            #line default
            #line hidden
            this.Write("            { ");
            
            #line 290 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Key));
            
            #line default
            #line hidden
            this.Write(",\"");
            
            #line 290 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Value));
            
            #line default
            #line hidden
            this.Write("\" },\r\n");
            
            #line 291 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
		} 
            
            #line default
            #line hidden
            this.Write("        };\r\n");
            
            #line 293 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
	} 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 295 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
 if (Data.UpdateEntityNavigatePropertyPermissions.Count > 0) { 
            
            #line default
            #line hidden
            this.Write(@"        protected override Dictionary<string, int> UpdateEntityNavigatePropertyPermissions
        {
            get { return _UpdateEntityNavigatePropertyPermissions; }
        }
        private static readonly Dictionary<string, int> _UpdateEntityNavigatePropertyPermissions = new Dictionary<string, int>()
        {
");
            
            #line 302 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
		foreach (var item in Data.UpdateEntityNavigatePropertyPermissions) {
            
            #line default
            #line hidden
            this.Write("            { \"");
            
            #line 303 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Key));
            
            #line default
            #line hidden
            this.Write("\",");
            
            #line 303 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Value));
            
            #line default
            #line hidden
            this.Write(" },\r\n");
            
            #line 304 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
		} 
            
            #line default
            #line hidden
            this.Write("        };\r\n");
            
            #line 306 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
	} 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 308 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
 if (Configure.DataFilter != null && Configure.DataFilter.Filters.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("        public override IQueryable<");
            
            #line 309 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Documnet.Name));
            
            #line default
            #line hidden
            this.Write("> Query\r\n        {\r\n            get \r\n\t\t\t{ \r\n\t\t\t\tif(_Query == null)\r\n\t\t\t\t{\r\n\t\t\t\t\t" +
                    "_Query = base.Query;\r\n");
            
            #line 316 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
 WriteFilterCode(Configure.DataFilter); 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t}\r\n\t\t\t\treturn _Query; \r\n\t\t\t}\r\n        }\r\n        private IQueryable<");
            
            #line 321 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Documnet.Name));
            
            #line default
            #line hidden
            this.Write("> _Query;\r\n");
            
            #line 322 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t}\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 325 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
 void WriteFilterCode(EntityQuery filter) { 
        
        #line default
        #line hidden
        
        #line 325 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
this.Write("\t\t\t\t\tvar _builder = new DynamicFilterBuilder<");

        
        #line default
        #line hidden
        
        #line 326 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(Documnet.Name));

        
        #line default
        #line hidden
        
        #line 326 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
this.Write(">(this);\r\n\t\t\t\t\tvar _g0 = _builder.Root;\r\n\t\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 328 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(WriteFilter(filter)));

        
        #line default
        #line hidden
        
        #line 328 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
this.Write("\r\n\t\t\t\t\tvar _exp = _g0.Expression;\r\n\t\t\t\t\tif(_exp != null)\r\n\t\t\t\t\t\t_Query = _Query.W" +
        "here(_exp);\r\n");

        
        #line default
        #line hidden
        
        #line 332 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\ControllerTemplate.tt"
 } 
        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class ControllerTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
