// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 15.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Wilmar.Build.Core.Service.Default.ServiceTemplate
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Wilmar.Foundation;
    using Wilmar.Model.Core.Definitions;
    using Wilmar.Model.Core.Definitions.Entities;
    using Wilmar.Model.Core.Definitions.Entities.Members;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class DataContextTemplate : DataContextTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System;\r\nusing System.Data.Entity;\r\nusing System.Data.Entity.Migrations;\r\nu" +
                    "sing System.Linq;\r\nusing System.Data.SqlClient;\r\nusing System.Data.Entity.ModelC" +
                    "onfiguration.Conventions;\r\nusing Wilmar.Service.Common.ProjectBase;\r\nusing Wilma" +
                    "r.");
            
            #line 17 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.Identity));
            
            #line default
            #line hidden
            this.Write(".Service.Models;\r\n\r\nnamespace Wilmar.");
            
            #line 19 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.Identity));
            
            #line default
            #line hidden
            this.Write(".Service\r\n{\r\n");
            
            #line 21 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
	string strDataContextName = Documnet.Name + "DataContext"; 
            
            #line default
            #line hidden
            this.Write("\r\n\tpublic class ");
            
            #line 23 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.ClassName));
            
            #line default
            #line hidden
            this.Write(" : DataContextBase\r\n\t{\r\n\t\tpublic static readonly Wilmar.Foundation.Projects.Confi" +
                    "gures.DatabaseConfigureItem ___DatabaseConfigureItem = GetConfigure(typeof(");
            
            #line 25 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.ClassName));
            
            #line default
            #line hidden
            this.Write(").Assembly,");
            
            #line 25 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Documnet.Id));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n\t\tpublic ");
            
            #line 27 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.ClassName));
            
            #line default
            #line hidden
            this.Write("(string nameOrConnectionString, string providerName)\r\n\t\t\t:base(nameOrConnectionSt" +
                    "ring, providerName)\r\n\t\t{ }\r\n\r\n\t\tpublic ");
            
            #line 31 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.ClassName));
            
            #line default
            #line hidden
            this.Write("()\r\n\t\t\t:base(___DatabaseConfigureItem.ConnectionString, ___DatabaseConfigureItem." +
                    "ProviderName)\r\n\t\t{\r\n\t\t    this.Database.CommandTimeout = 120;//2Mins\r\n");
            
            #line 35 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
 if(Documnet.BlockModelValidate) { 
            
            #line default
            #line hidden
            this.Write("\t\t\tDatabase.SetInitializer<");
            
            #line 36 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.ClassName));
            
            #line default
            #line hidden
            this.Write(">(null);\r\n");
            
            #line 37 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
	} else { 
            
            #line default
            #line hidden
            this.Write("\t\t\tvar config = GetConfigure(typeof(");
            
            #line 38 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.ClassName));
            
            #line default
            #line hidden
            this.Write(").Assembly,");
            
            #line 38 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Documnet.Id));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\tif(!config.AutoMigration && !config.AllowDataLoss)\r\n\t\t\t\tDatabase.SetInitia" +
                    "lizer<");
            
            #line 40 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.ClassName));
            
            #line default
            #line hidden
            this.Write(">(null);\r\n\t\t\telse\r\n\t\t\t\tDatabase.SetInitializer<");
            
            #line 42 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.ClassName));
            
            #line default
            #line hidden
            this.Write(">(CreateInitializer<");
            
            #line 42 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.ClassName));
            
            #line default
            #line hidden
            this.Write(">(config.AutoMigration, config.AllowDataLoss));\r\n");
            
            #line 43 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
	} 
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n");
            
            #line 46 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
	foreach (var entity in Data.Entitys.Values) {
            
            #line default
            #line hidden
            this.Write("\t\t\r\n\t\tpublic virtual DbSet<");
            
            #line 48 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.ClassName));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 48 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.ClassName));
            
            #line default
            #line hidden
            this.Write("s { get; set; }\r\n");
            
            #line 49 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
	} 
            
            #line default
            #line hidden
            this.Write("\r\n\t\tprotected override void OnModelCreating(DbModelBuilder builder)\r\n\t\t{\t\t\r\n\t\t\tba" +
                    "se.OnModelCreating(builder);\r\n");
            
            #line 54 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
 if (AllowRenameProcedureParameter && EntityStoreProduceNames.Length > 0) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t var _dic = ResetStoreProceduresParameter(builder, temp=>\r\n\t\t\t {\r\n");
            
            #line 57 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
	foreach (var item in Data.Relations) {
            
            #line default
            #line hidden
            this.Write("\t\t\t\ttemp.Entity<");
            
            #line 58 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.FromEntity.ClassName));
            
            #line default
            #line hidden
            this.Write(">().Has");
            
            #line 58 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetHasName(item)));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 58 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetHasProperty(item)));
            
            #line default
            #line hidden
            this.Write(").With");
            
            #line 58 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetWithName(item)));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 58 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetWithProperty(item)));
            
            #line default
            #line hidden
            this.Write(")");
            
            #line 58 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetForeignKey(item)));
            
            #line default
            #line hidden
            
            #line 58 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetCascadeOnDelete(item)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 59 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
	} 
            
            #line default
            #line hidden
            this.Write("\t\t\t \r\n\t\t\t }, new Type[] \r\n\t\t\t { \r\n");
            
            #line 62 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
	foreach (var name in EntityStoreProduceNames) {
            
            #line default
            #line hidden
            this.Write("\t\t\t\ttypeof(");
            
            #line 63 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("), \r\n");
            
            #line 64 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
	} 
            
            #line default
            #line hidden
            this.Write("\t\t\t });\r\n\r\n");
            
            #line 67 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
	foreach (var name in EntityStoreProduceNames) {
            
            #line default
            #line hidden
            this.Write("            ProcessStoreProceduresParameter<");
            
            #line 68 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write(">(builder, _dic[typeof(");
            
            #line 68 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write(")]);\r\n");
            
            #line 69 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
	} 
            
            #line default
            #line hidden
            
            #line 70 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
	} 
            
            #line default
            #line hidden
            this.Write("\r\n ");
            
            #line 72 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
	foreach (var item in Data.Relations) {
            
            #line default
            #line hidden
            this.Write("\t\t\tbuilder.Entity<");
            
            #line 73 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.FromEntity.ClassName));
            
            #line default
            #line hidden
            this.Write(">().Has");
            
            #line 73 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetHasName(item)));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 73 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetHasProperty(item)));
            
            #line default
            #line hidden
            this.Write(").With");
            
            #line 73 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetWithName(item)));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 73 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetWithProperty(item)));
            
            #line default
            #line hidden
            this.Write(")");
            
            #line 73 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetForeignKey(item)));
            
            #line default
            #line hidden
            
            #line 73 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetCascadeOnDelete(item)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 74 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\DataContextTemplate.tt"
	} 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t}\r\n\t\t\t\r\n\t}\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class DataContextTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
