// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 15.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Wilmar.Build.Core.Service.Default.ServiceTemplate
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Wilmar.Foundation;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class EntityTemplate : EntityTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System;\r\n\r\nnamespace Wilmar.");
            
            #line 9 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.Identity));
            
            #line default
            #line hidden
            this.Write(".Service.Models\r\n{\r\n\t");
            
            #line 11 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.GenerateCode()));
            
            #line default
            #line hidden
            this.Write("\r\n\tpublic class ");
            
            #line 12 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.ClassName));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 13 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
 if (!string.IsNullOrEmpty(Data.BaseClassName)) { 
            
            #line default
            #line hidden
            this.Write("\t\t: ");
            
            #line 14 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.BaseClassName));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 15 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
} 
            
            #line default
            #line hidden
            this.Write("\t{\r\n");
            
            #line 17 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
	foreach (var member in Data.PrimaryPropertys.Values.Where(a => !a.IsInherit)) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 19 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.GenerateCode()));
            
            #line default
            #line hidden
            this.Write("\r\n        public ");
            
            #line 20 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyType.TypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 20 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            get { return _");
            
            #line 22 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n            set { _");
            
            #line 23 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write(" = value; }\r\n        }\r\n        private ");
            
            #line 25 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyType.TypeName));
            
            #line default
            #line hidden
            this.Write(" _");
            
            #line 25 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            
            #line 25 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(WriteDefaultValue(member.GetDefaultValue())));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 26 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
	} 
            
            #line default
            #line hidden
            
            #line 27 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
	foreach (var member in Data.CommonPropertys.Values.Where(a => !a.IsInherit)) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 29 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.GenerateCode()));
            
            #line default
            #line hidden
            this.Write("\r\n        public ");
            
            #line 30 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyType.TypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 30 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            get { return _");
            
            #line 32 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n            set { _");
            
            #line 33 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write(" = value; }\r\n        }\r\n        private ");
            
            #line 35 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyType.TypeName));
            
            #line default
            #line hidden
            this.Write(" _");
            
            #line 35 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            
            #line 35 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(WriteDefaultValue(member.GetDefaultValue())));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 36 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
	} 
            
            #line default
            #line hidden
            
            #line 37 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
	foreach (var member in Data.ColumnPropertys.Values.Where(a => !a.IsInherit)) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 39 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.GenerateCode()));
            
            #line default
            #line hidden
            this.Write("\r\n        public ");
            
            #line 40 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyType.TypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 40 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            get { return _");
            
            #line 42 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n            set { _");
            
            #line 43 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write(" = value; }\r\n        }\r\n        private ");
            
            #line 45 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyType.TypeName));
            
            #line default
            #line hidden
            this.Write(" _");
            
            #line 45 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            
            #line 45 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(WriteDefaultValue(member.GetDefaultValue())));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 46 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
	} 
            
            #line default
            #line hidden
            
            #line 47 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
	foreach (var member in Data.CalculatePropertys.Values.Where(a => !a.IsInherit)) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 49 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.GenerateCode()));
            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic ");
            
            #line 50 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyType.TypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 50 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t{ \r\n\t\t\tget { ");
            
            #line 52 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Member.Body));
            
            #line default
            #line hidden
            this.Write(" } \r\n\t\t}\r\n");
            
            #line 54 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
	} 
            
            #line default
            #line hidden
            
            #line 55 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
	foreach (var member in Data.NavigationPropertys.Values.Where(a => !a.IsInherit)) { 
            
            #line default
            #line hidden
            
            #line 56 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
		if (member.PropertyType.IsCollection) { 
            
            #line default
            #line hidden
            this.Write("\t\tpublic virtual System.Collections.Generic.ICollection<");
            
            #line 57 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyType.TypeName));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 57 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t{ \r\n\t\t\tget { return _");
            
            #line 59 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write(" ?? (_");
            
            #line 59 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write(" = new System.Collections.Generic.HashSet<");
            
            #line 59 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyType.EntityType.ClassName));
            
            #line default
            #line hidden
            this.Write(">()); } \r\n\t\t}\r\n\t\tprivate System.Collections.Generic.HashSet<");
            
            #line 61 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyType.EntityType.ClassName));
            
            #line default
            #line hidden
            this.Write("> _");
            
            #line 61 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 62 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
		} else { 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 63 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.GenerateCode()));
            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic virtual ");
            
            #line 64 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyType.TypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 64 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 65 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
		} 
            
            #line default
            #line hidden
            
            #line 66 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
	} 
            
            #line default
            #line hidden
            this.Write("\t}\r\n\r\n");
            
            #line 69 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
 if(IsFast) { 
            
            #line default
            #line hidden
            this.Write("\tpublic class ");
            
            #line 70 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.ClassName));
            
            #line default
            #line hidden
            this.Write("DimProxy\r\n\t{\r\n");
            
            #line 72 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
	foreach (var member in Data.PrimaryPropertys.Values.Where(a => !a.IsInherit)) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 74 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.GenerateCode()));
            
            #line default
            #line hidden
            this.Write("\r\n        public ");
            
            #line 75 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyType.TypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 75 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            get { return _");
            
            #line 77 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n            set { _");
            
            #line 78 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write(" = value; }\r\n        }\r\n        private ");
            
            #line 80 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyType.TypeName));
            
            #line default
            #line hidden
            this.Write(" _");
            
            #line 80 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            
            #line 80 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(WriteDefaultValue(member.GetDefaultValue())));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 81 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
	} 
            
            #line default
            #line hidden
            
            #line 82 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
	foreach (var member in Data.ColumnPropertys.Values.Where(a => !a.IsInherit)) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 84 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.GenerateCode()));
            
            #line default
            #line hidden
            this.Write("\r\n        public ");
            
            #line 85 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyType.TypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 85 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            get { return _");
            
            #line 87 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n            set { _");
            
            #line 88 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write(" = value; }\r\n        }\r\n        private ");
            
            #line 90 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyType.TypeName));
            
            #line default
            #line hidden
            this.Write(" _");
            
            #line 90 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            
            #line 90 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(WriteDefaultValue(member.GetDefaultValue())));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 91 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
	} 
            
            #line default
            #line hidden
            
            #line 92 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
	foreach (var member in Data.DimMemberPropertys.Values.Where(a => !a.IsInherit)) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 94 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.GenerateCode()));
            
            #line default
            #line hidden
            this.Write("\r\n        public ");
            
            #line 95 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyType.TypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 95 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            get { return _");
            
            #line 97 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n            set { _");
            
            #line 98 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write(" = value; }\r\n        }\r\n        private ");
            
            #line 100 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyType.TypeName));
            
            #line default
            #line hidden
            this.Write(" _");
            
            #line 100 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            
            #line 100 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(WriteDefaultValue(member.GetDefaultValue())));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 101 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
	} 
            
            #line default
            #line hidden
            this.Write("\t}\r\n");
            
            #line 103 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Service\Default\ServiceTemplate\EntityTemplate.tt"
	} 
            
            #line default
            #line hidden
            this.Write("\r\n}\r\n\r\n\r\n\r\n\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class EntityTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
