// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 15.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Wilmar.Build.Core.Ionic.Default.Template
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class ModelTemplate : ModelTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("import { Component } from \'@angular/core\';\nimport { ModelBase, Model, ModelProper" +
                    "ty, ModelKey, DataType as System, ModelNavigation } from \'../../../platform\';\r\n\r" +
                    "\n");
            
            #line 3 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
 foreach (var member in ImportMember) { 
            
            #line default
            #line hidden
            this.Write("import { ");
            
            #line 4 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Key));
            
            #line default
            #line hidden
            this.Write(" } from \'./");
            
            #line 4 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Key));
            
            #line default
            #line hidden
            this.Write("\';\r\n");
            
            #line 5 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n@Model({\n    name: \"");
            
            #line 7 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Documnet.Name));
            
            #line default
            #line hidden
            this.Write("\"\n})\nexport class ");
            
            #line 7 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Documnet.Name));
            
            #line default
            #line hidden
            this.Write(" extends ModelBase {\n    constructor() { super(); }\n\n\t");
            
            #line 7 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
 foreach (var member in PrimaryPropertys) { 
            
            #line default
            #line hidden
            this.Write("/**\r\n     * ");
            
            #line 8 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Item1));
            
            #line default
            #line hidden
            this.Write("\r\n     */\r\n    @ModelKey({ name: \"");
            
            #line 10 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Key));
            
            #line default
            #line hidden
            this.Write("\", dataType: System.");
            
            #line 10 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Item2));
            
            #line default
            #line hidden
            this.Write(" })\r\n    public ");
            
            #line 11 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Key));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 11 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Item3));
            
            #line default
            #line hidden
            this.Write(";\r\n\t");
            
            #line 12 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"

	}
	
            
            #line default
            #line hidden
            this.Write("\n\n\t");
            
            #line 12 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
 foreach (var member in ColumnPropertys) { 
            
            #line default
            #line hidden
            this.Write("/**\r\n     * ");
            
            #line 13 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Item1));
            
            #line default
            #line hidden
            this.Write("\r\n     */\r\n    @ModelProperty({ name: \"");
            
            #line 15 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Key));
            
            #line default
            #line hidden
            this.Write("\", dataType: System.");
            
            #line 15 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Item2));
            
            #line default
            #line hidden
            this.Write(" })\r\n    public ");
            
            #line 16 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Key));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 16 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Item3));
            
            #line default
            #line hidden
            this.Write(";\r\n\t");
            
            #line 17 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"

	}
	
            
            #line default
            #line hidden
            this.Write("\n\n\t");
            
            #line 17 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
 foreach (var member in CommonPropertys) { 
            
            #line default
            #line hidden
            this.Write("/**\r\n     * ");
            
            #line 18 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Item1));
            
            #line default
            #line hidden
            this.Write("\r\n     */\r\n    @Key({ name: \"");
            
            #line 20 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Key));
            
            #line default
            #line hidden
            this.Write("\", dataType: System.");
            
            #line 20 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Item2));
            
            #line default
            #line hidden
            this.Write(" })\r\n    public ");
            
            #line 21 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Key));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 21 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Item3));
            
            #line default
            #line hidden
            this.Write(";\r\n\t");
            
            #line 22 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"

	}
	
            
            #line default
            #line hidden
            this.Write("\n\n\t");
            
            #line 22 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
 foreach (var member in CalculatePropertys) { 
            
            #line default
            #line hidden
            this.Write("/**\r\n     * ");
            
            #line 23 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Item1));
            
            #line default
            #line hidden
            this.Write("\r\n     */\r\n    @Key({ name: \"");
            
            #line 25 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Key));
            
            #line default
            #line hidden
            this.Write("\", dataType: System.");
            
            #line 25 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Item2));
            
            #line default
            #line hidden
            this.Write(" })\r\n    public ");
            
            #line 26 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Key));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 26 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Item3));
            
            #line default
            #line hidden
            this.Write(";\r\n\t");
            
            #line 27 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"

	}
	
            
            #line default
            #line hidden
            this.Write("\t\r\n\t");
            
            #line 29 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
 foreach (var member in NavigationPropertys) { 
            
            #line default
            #line hidden
            this.Write("/**\r\n     * ");
            
            #line 30 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Item1));
            
            #line default
            #line hidden
            this.Write("\r\n     */\r\n\t");
            
            #line 32 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
 if(member.Value.Item4 == true) { 
            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 33 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
 if(!string.IsNullOrEmpty(member.Value.Item3)) { 
            
            #line default
            #line hidden
            this.Write("\t@ModelNavigation({ name: \"");
            
            #line 34 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Key));
            
            #line default
            #line hidden
            this.Write("\", entityTypeName: \"");
            
            #line 34 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Item2));
            
            #line default
            #line hidden
            this.Write("\", isScalar: true, foreignKeyNames: [\"");
            
            #line 34 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Item3));
            
            #line default
            #line hidden
            this.Write("\"] })\r\n\t");
            
            #line 35 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\t@ModelNavigation({ name: \"");
            
            #line 36 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Key));
            
            #line default
            #line hidden
            this.Write("\", entityTypeName: \"");
            
            #line 36 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Item2));
            
            #line default
            #line hidden
            this.Write("\", isScalar: true })\r\n\t");
            
            #line 37 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\tpublic ");
            
            #line 38 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Key));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 38 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Item2));
            
            #line default
            #line hidden
            this.Write(";\n\t");
            
            #line 38 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\t@ModelNavigation({ name: \"");
            
            #line 39 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Key));
            
            #line default
            #line hidden
            this.Write("\", entityTypeName: \"");
            
            #line 39 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Item2));
            
            #line default
            #line hidden
            this.Write("\", isScalar: false })\r\n    public ");
            
            #line 40 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Key));
            
            #line default
            #line hidden
            this.Write(": Array<");
            
            #line 40 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Item2));
            
            #line default
            #line hidden
            this.Write(">;\r\n\t");
            
            #line 41 "D:\works\KDS3_NEW\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\ModelTemplate.tt"
 }} 
            
            #line default
            #line hidden
            this.Write("\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class ModelTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
