// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 15.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Wilmar.Build.Core.Ionic.Default.Template
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class PageMainTemplate : PageMainTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"import { Component, Injector } from '@angular/core';
import { IonicPage, ScreenBase, Utils, EntityQuery, config, EntityManager, UriBuilderODataAdapter, DataService, EntityManagerConfig, MetadataHelper, AutoGeneratedKeyType, DataType, EntityKey, EntityType, RemoteDataSet, RemoteDataObject, LocalDataSet, LocalDataObject, Screen, ScreenMethod, ScreenProperty, ParameterType } from '../../platform';

");
            
            #line 3 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 foreach (var member in ImportEntity) { 
            
            #line default
            #line hidden
            this.Write("import * as ");
            
            #line 4 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value));
            
            #line default
            #line hidden
            this.Write("Model from \"./models/");
            
            #line 4 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value));
            
            #line default
            #line hidden
            this.Write("\"\n");
            
            #line 4 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 7 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 foreach (var item in DataSetData) { 
            
            #line default
            #line hidden
            
            #line 8 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 if(string.IsNullOrEmpty(item.Value.EntityName)) { 
            
            #line default
            #line hidden
            this.Write("class Custom");
            
            #line 9 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Value.Name));
            
            #line default
            #line hidden
            this.Write(" {\n\tconstructor() { }\n");
            
            #line 9 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\nclass Custom");
            
            #line 9 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Value.Name));
            
            #line default
            #line hidden
            this.Write(" extends ");
            
            #line 9 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Value.EntityName));
            
            #line default
            #line hidden
            this.Write("Model.");
            
            #line 9 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Value.EntityName));
            
            #line default
            #line hidden
            this.Write(" {\n\tconstructor() { super(); }\n");
            
            #line 9 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\n\t");
            
            #line 9 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 foreach (var member in item.Value.SelectedItemMembers) { 
            
            #line default
            #line hidden
            this.Write("/**\r\n\t* ");
            
            #line 10 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Title));
            
            #line default
            #line hidden
            this.Write("\r\n\t*/\r\n\t@ScreenProperty()\r\n\t");
            
            #line 13 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 if(member.DefaultValue == null) { 
            
            #line default
            #line hidden
            this.Write("\tpublic ");
            
            #line 14 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 14 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.DataType));
            
            #line default
            #line hidden
            this.Write(";\r\n\t");
            
            #line 15 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 16 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 if(member.DataType == "number" || member.DataType == "boolean") { 
            
            #line default
            #line hidden
            this.Write("\tpublic ");
            
            #line 17 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 17 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.DataType));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 17 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.DefaultValue));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t");
            
            #line 18 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\tpublic ");
            
            #line 19 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 19 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.DataType));
            
            #line default
            #line hidden
            this.Write(" = \"");
            
            #line 19 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.DefaultValue));
            
            #line default
            #line hidden
            this.Write("\";\r\n\t\t");
            
            #line 20 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\n\t");
            
            #line 20 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\n\t");
            
            #line 20 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\n\n\t");
            
            #line 20 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 foreach (var member in item.Value.SelectedItemMethods) { 
            
            #line default
            #line hidden
            this.Write("/**\r\n\t* ");
            
            #line 21 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Title));
            
            #line default
            #line hidden
            this.Write("\r\n\t*/\r\n\t@ScreenMethod({ name:\"");
            
            #line 23 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write("\", parameters:[");
            
            #line 23 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ParamsBind));
            
            #line default
            #line hidden
            this.Write("]})\r\n\tpublic ");
            
            #line 24 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 24 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Params));
            
            #line default
            #line hidden
            this.Write(") {\r\n\t\t");
            
            #line 25 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Body));
            
            #line default
            #line hidden
            this.Write("\r\n\t}\r\n\t");
            
            #line 27 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\n}\nclass Custom");
            
            #line 27 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Value.Type));
            
            #line default
            #line hidden
            
            #line 27 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Value.Name));
            
            #line default
            #line hidden
            this.Write(" extends ");
            
            #line 27 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Value.Type));
            
            #line default
            #line hidden
            this.Write("<Custom");
            
            #line 27 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Value.Name));
            
            #line default
            #line hidden
            this.Write("> {\n\t");
            
            #line 27 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 if(item.Value.Type == "RemoteDataObject" || item.Value.Type == "LocalDataObject") { 
            
            #line default
            #line hidden
            this.Write("\n\tconstructor(modeName: string) {\n\t\tsuper(modeName);\n\t}\n\t");
            
            #line 27 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\n\tconstructor(modeName: string, options: object) {\n\t\tsuper(modeName, options);\n\t}" +
                    "\n\t");
            
            #line 27 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\n\n\t");
            
            #line 27 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 foreach (var member in item.Value.DataPropertys) { 
            
            #line default
            #line hidden
            this.Write("/**\r\n\t* ");
            
            #line 28 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Title));
            
            #line default
            #line hidden
            this.Write("\r\n\t*/\r\n\t@ScreenProperty()\r\n\t");
            
            #line 31 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 if(member.DefaultValue == null) { 
            
            #line default
            #line hidden
            this.Write("\tpublic ");
            
            #line 32 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 32 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.DataType));
            
            #line default
            #line hidden
            this.Write(";\r\n\t");
            
            #line 33 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 34 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 if(member.DataType == "number" || member.DataType == "boolean") { 
            
            #line default
            #line hidden
            this.Write("\tpublic ");
            
            #line 35 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 35 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.DataType));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 35 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.DefaultValue));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t");
            
            #line 36 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\tpublic ");
            
            #line 37 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 37 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.DataType));
            
            #line default
            #line hidden
            this.Write(" = \"");
            
            #line 37 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.DefaultValue));
            
            #line default
            #line hidden
            this.Write("\";\r\n\t\t");
            
            #line 38 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\n\t");
            
            #line 38 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\n\t");
            
            #line 38 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\n\n\t");
            
            #line 38 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 foreach (var member in item.Value.DataEvents) { 
            
            #line default
            #line hidden
            this.Write("/**\r\n\t* ");
            
            #line 39 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Title));
            
            #line default
            #line hidden
            this.Write("\r\n\t*/\r\n\tpublic ");
            
            #line 41 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write("() {\r\n\t\t");
            
            #line 42 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Body));
            
            #line default
            #line hidden
            this.Write("\r\n\t}\r\n\t");
            
            #line 44 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\n\n\t");
            
            #line 44 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 foreach (var member in item.Value.DataMethods) { 
            
            #line default
            #line hidden
            this.Write("/**\r\n\t* ");
            
            #line 45 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Title));
            
            #line default
            #line hidden
            this.Write("\r\n\t*/\r\n\t@ScreenMethod({ name:\"");
            
            #line 47 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write("\", parameters:[");
            
            #line 47 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ParamsBind));
            
            #line default
            #line hidden
            this.Write("]})\r\n\tpublic ");
            
            #line 48 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 48 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Params));
            
            #line default
            #line hidden
            this.Write(") {\r\n\t\t");
            
            #line 49 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Body));
            
            #line default
            #line hidden
            this.Write("\r\n\t}\r\n\t");
            
            #line 51 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\n}\n");
            
            #line 51 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 54 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 foreach (var member in ScreenParamData) { 
            
            #line default
            #line hidden
            this.Write("@Screen({ \r\nname:\"");
            
            #line 56 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Key));
            
            #line default
            #line hidden
            this.Write("\",\r\nparameters:{ ");
            
            #line 57 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Content));
            
            #line default
            #line hidden
            this.Write(" }\r\n})\r\n");
            
            #line 59 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\r\n@IonicPage()\r\n@Component({\r\n  templateUrl: \'./pages/StartupPage/StartupPage.h" +
                    "tml\'\r\n})\r\nexport class ");
            
            #line 66 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Compile.Project.Identity));
            
            #line default
            #line hidden
            this.Write(" extends ScreenBase {\n  constructor(private injector: Injector) {\n    super(injec" +
                    "tor);\n  }\n  \n\t");
            
            #line 66 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 foreach (var member in PropertyData) { 
            
            #line default
            #line hidden
            this.Write("/**\r\n\t* ");
            
            #line 67 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Title));
            
            #line default
            #line hidden
            this.Write("\r\n\t*/\r\n\t@ScreenProperty()\r\n\t");
            
            #line 70 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 if(member.Value.DefaultValue == null) { 
            
            #line default
            #line hidden
            this.Write("\tpublic ");
            
            #line 71 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Name));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 71 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.DataType));
            
            #line default
            #line hidden
            this.Write(";\r\n\t");
            
            #line 72 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 73 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 if(member.Value.DataType == "number" || member.Value.DataType == "boolean") { 
            
            #line default
            #line hidden
            this.Write("\tpublic ");
            
            #line 74 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Name));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 74 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.DataType));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 74 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.DefaultValue));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t");
            
            #line 75 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\tpublic ");
            
            #line 76 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Name));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 76 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.DataType));
            
            #line default
            #line hidden
            this.Write(" = \"");
            
            #line 76 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.DefaultValue));
            
            #line default
            #line hidden
            this.Write("\";\r\n\t\t");
            
            #line 77 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\n\t");
            
            #line 77 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\n\t");
            
            #line 77 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\n\n\t");
            
            #line 77 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 foreach (var member in EventData) { 
            
            #line default
            #line hidden
            this.Write("/**\r\n\t* ");
            
            #line 78 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Title));
            
            #line default
            #line hidden
            this.Write("\r\n\t*/\r\n\tpublic ");
            
            #line 80 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Name));
            
            #line default
            #line hidden
            this.Write("() {\r\n\t\t");
            
            #line 81 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Body));
            
            #line default
            #line hidden
            this.Write("\r\n\t}\r\n\t");
            
            #line 83 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\n\n\t");
            
            #line 83 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 foreach (var member in MethodData) { 
            
            #line default
            #line hidden
            this.Write("/**\r\n\t* ");
            
            #line 84 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Title));
            
            #line default
            #line hidden
            this.Write("\r\n\t*/\r\n\t@ScreenMethod({ name:\"");
            
            #line 86 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Name));
            
            #line default
            #line hidden
            this.Write("\", parameters:[");
            
            #line 86 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.ParamsBind));
            
            #line default
            #line hidden
            this.Write("]})\r\n\tpublic ");
            
            #line 87 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 87 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Params));
            
            #line default
            #line hidden
            this.Write(") {\r\n\t\t");
            
            #line 88 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Body));
            
            #line default
            #line hidden
            this.Write("\r\n\t}\r\n\t");
            
            #line 90 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\n\n\t");
            
            #line 90 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 foreach (var member in DataSetData) { 
            
            #line default
            #line hidden
            this.Write("/**\r\n\t* ");
            
            #line 91 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Title));
            
            #line default
            #line hidden
            this.Write("\r\n\t*/\r\n\t@ScreenProperty({ \r\n\tname: \"");
            
            #line 94 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Name));
            
            #line default
            #line hidden
            this.Write("\",\r\n\ttype: [Custom");
            
            #line 95 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Type));
            
            #line default
            #line hidden
            
            #line 95 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Name));
            
            #line default
            #line hidden
            this.Write(", Custom");
            
            #line 95 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Name));
            
            #line default
            #line hidden
            this.Write("],\r\n\toptions: { ");
            
            #line 96 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Options));
            
            #line default
            #line hidden
            this.Write(" }\r\n\t})\r\n\tpublic ");
            
            #line 98 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Name));
            
            #line default
            #line hidden
            this.Write(": Custom");
            
            #line 98 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Type));
            
            #line default
            #line hidden
            
            #line 98 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Value.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t");
            
            #line 99 "D:\KDS3\code\Wilmar.Platform\src\Wilmar.Build.Core\Ionic\Default\Template\PageMainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class PageMainTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
